import type { MallCatalogItem, MallData } from '../../types';

const DEFAULT_CATALOG: MallCatalogItem[] = [
  {
    id: 'mall-item-soft-tee',
    title: '柔棉落肩短袖',
    subtitle: '宽松日常 / 低饱和配色',
    category: '男装',
    subCategory: 'T 恤',
    price: 129,
    tags: ['日常', '宽松', '通勤'],
    sceneTags: ['通勤', '周末', '自己买'],
    styleTags: ['简约', '柔和'],
    sensitivity: 'normal',
    destinationKinds: ['self', 'gift'],
    isWearable: true,
    media: {
      fallbackEmoji: '👕',
      fallbackIcon: 'package',
      templateKey: 'soft-tee',
      accentColor: '#8aa0b7',
      backgroundPreset: 'mist-blue',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '一件看起来不费力、穿起来也不会太拘束的宽松短袖。',
      detailDescription: '这件短袖走的是很轻的日常路线，肩线略微下落，布料看起来柔软，适合白天出门、随手套上或者周末慢慢穿。它不强调夸张的存在感，更像那种会被反复拿出来穿的稳定日常单品。买完后会进入你的衣柜，适合和其他基础款一起搭配。',
      recommendationReason: '最近更适合补一些能高频使用的日常单品，这件比明显风格化的衣服更稳。',
    },
  },
  {
    id: 'mall-item-striped-pajama',
    title: '条纹居家睡衣套装',
    subtitle: '柔软面料 / 睡前放松',
    category: '睡眠',
    subCategory: '居家服',
    price: 199,
    tags: ['睡前', '居家', '舒适'],
    sceneTags: ['睡前', '宅家', '自己买'],
    styleTags: ['轻松', '安静'],
    sensitivity: 'normal',
    destinationKinds: ['self', 'gift'],
    isWearable: true,
    media: {
      fallbackEmoji: '🛌',
      fallbackIcon: 'package',
      templateKey: 'striped-pajama',
      accentColor: '#7f95a8',
      backgroundPreset: 'night-blue',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '更偏睡前和居家的那类软绵绵单品，看着就像会让人慢下来。',
      detailDescription: '这是一套适合夜里换上的居家睡衣，条纹不会太抢眼，整体更偏安静和放松。面料观感柔和，适合晚上洗完澡后直接穿着待在房间里，也适合当作“今晚好好休息”那种生活化补货。买完后会进入你的衣柜。',
      recommendationReason: '如果你最近更常在晚上逛商城，这类东西会比纯装饰更容易马上进入生活。',
    },
  },
  {
    id: 'mall-item-candle',
    title: '白茶香氛蜡烛',
    subtitle: '玻璃杯体 / 柔和香调',
    category: '家居',
    subCategory: '香薰',
    price: 89,
    tags: ['香氛', '房间', '氛围'],
    sceneTags: ['睡前', '房间', '自己买'],
    styleTags: ['温柔', '安静'],
    sensitivity: 'normal',
    destinationKinds: ['self', 'gift', 'shared_space'],
    isDisplayable: true,
    media: {
      fallbackEmoji: '🕯️',
      fallbackIcon: 'package',
      templateKey: 'white-tea-candle',
      accentColor: '#d2a56a',
      backgroundPreset: 'warm-amber',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '很适合放在床边或桌角，让房间慢慢有一点被照顾过的感觉。',
      detailDescription: '这是一只更适合放在房间里的香氛蜡烛，玻璃杯体让它看起来不会太厚重，白茶调也更偏柔和、干净，不会一下子把整个空间塞满。它适合在睡前、看书、发呆或者想把房间氛围稍微收一收的时候点起来。买完后可以进入你的物品，也可以后续放进共同空间陈列。',
      recommendationReason: '最近如果你更在意房间氛围，这类小东西比大型家居更容易马上带来变化。',
    },
  },
  {
    id: 'mall-item-night-lamp',
    title: '奶油小夜灯',
    subtitle: '暖色氛围 / 桌面摆放',
    category: '共同空间',
    subCategory: '灯光氛围',
    price: 149,
    tags: ['灯光', '桌面', '摆件'],
    sceneTags: ['房间', '共同空间', '睡前'],
    styleTags: ['奶油色', '温和'],
    sensitivity: 'normal',
    destinationKinds: ['self', 'gift', 'shared_space'],
    isDisplayable: true,
    media: {
      fallbackEmoji: '💡',
      fallbackIcon: 'package',
      templateKey: 'night-lamp',
      accentColor: '#d8b06b',
      backgroundPreset: 'soft-gold',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '更像一盏会把角落照得刚好的灯，不喧闹，但很容易被记住。',
      detailDescription: '这盏小夜灯适合摆在床头、桌角或共同空间的某个角落。它的存在感不靠复杂造型，而是靠柔和的暖色和稳定的陪伴感。无论是自己房间还是后续共同空间，它都更像一种慢慢沉淀下来的氛围物。买完后可以放入物品，后续也可以转入共同空间。',
      recommendationReason: '如果你最近在补充会长期待在空间里的东西，这类小灯比一次性小物更有留存感。',
    },
  },
  {
    id: 'mall-item-mug',
    title: '磨砂陶瓷马克杯',
    subtitle: '低调手感 / 日常高频',
    category: '家居',
    subCategory: '杯具',
    price: 69,
    tags: ['杯子', '日常', '手感'],
    sceneTags: ['书桌', '厨房', '自己买'],
    styleTags: ['简洁', '耐看'],
    sensitivity: 'normal',
    destinationKinds: ['self', 'gift'],
    media: {
      fallbackEmoji: '☕',
      fallbackIcon: 'package',
      templateKey: 'matte-mug',
      accentColor: '#a88269',
      backgroundPreset: 'coffee-brown',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '不是惊艳型物品，但会因为手感和使用频率慢慢变成偏爱。',
      detailDescription: '这只马克杯更偏磨砂质感和稳定实用的路线，不是那种为了拍照而存在的摆设，而是会被真正常用起来的日常物。它适合热饮、水、夜里随手放在桌边，也适合和其他简洁家居一起出现。买完后会进入你的物品。',
      recommendationReason: '如果你想先补一些真正会高频使用的生活物，它会比纯装饰更有存在感。',
    },
  },
  {
    id: 'mall-item-photo-frame',
    title: '木质相框摆件',
    subtitle: '轻纪念感 / 桌面陈列',
    category: '共同空间',
    subCategory: '相框挂饰',
    price: 119,
    tags: ['纪念', '陈列', '桌面'],
    sceneTags: ['共同空间', '礼物', '纪念'],
    styleTags: ['木质', '温暖'],
    sensitivity: 'normal',
    destinationKinds: ['self', 'gift', 'shared_space'],
    isDisplayable: true,
    media: {
      fallbackEmoji: '🖼️',
      fallbackIcon: 'package',
      templateKey: 'photo-frame',
      accentColor: '#b78a62',
      backgroundPreset: 'oak-wood',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '更适合被放着慢慢看，而不是买完就忘记的那类小纪念物。',
      detailDescription: '这是一个适合桌面和共同空间的木质相框摆件，观感偏温暖，不会太厚重，适合承接一点轻轻的纪念感。它既可以先作为你的物品，也可以在之后被放进共同空间，成为比较稳定的展示物。买完后优先进入你的物品。',
      recommendationReason: '如果你想补一些有纪念感但不太张扬的东西，这类摆件比大型装饰更容易融进空间。',
    },
  },
  {
    id: 'mall-item-satin-robe',
    title: '雾感缎面睡袍',
    subtitle: '轻薄贴肤 / 私密居家',
    category: '私密',
    subCategory: '私密穿搭',
    price: 239,
    tags: ['私密', '居家', '柔软'],
    sceneTags: ['夜里', '睡前', '自己买'],
    styleTags: ['雾面', '克制'],
    sensitivity: 'private',
    destinationKinds: ['self', 'gift'],
    isWearable: true,
    media: {
      fallbackEmoji: '🪶',
      fallbackIcon: 'package',
      templateKey: 'satin-robe',
      accentColor: '#8e6a72',
      backgroundPreset: 'oak-wood',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '更适合夜里和私密居家线的一件轻薄睡袍，存在感不张扬，但很容易让整晚的状态慢下来。',
      detailDescription: '这件睡袍更偏贴肤、轻薄和安静的路线，不会把氛围推得太用力，但会明显让居家状态更柔和。适合晚上洗完澡后慢慢换上，或者在想把整晚节奏放慢一点的时候穿。',
      recommendationReason: '如果你现在更想找一件只在自己的时间里慢慢用起来的东西，这类私密穿搭会比普通居家服更贴合。',
    },
  },
  {
    id: 'mall-item-night-care-set',
    title: '晚安护理礼盒',
    subtitle: '安静补货 / 私密清洁',
    category: '私密',
    subCategory: '护理清洁',
    price: 189,
    tags: ['护理', '私密', '夜里'],
    sceneTags: ['睡前', '夜里', '自己买'],
    styleTags: ['克制', '柔和'],
    sensitivity: 'private',
    destinationKinds: ['self', 'gift'],
    media: {
      fallbackEmoji: '🫧',
      fallbackIcon: 'package',
      templateKey: 'night-care-set',
      accentColor: '#7f5e66',
      backgroundPreset: 'coffee-brown',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '更像是一份安静补货，而不是高调存在的礼盒，适合把夜里的照顾感补齐一点。',
      detailDescription: '这套护理礼盒更强调干净、安静和低存在感，适合放在夜里使用，不会把私密照顾感做得太张扬。它更像是那种真正会被慢慢用起来、放进日常节奏里的补货。',
      recommendationReason: '如果你最近更在意夜里的状态和身体感受，这类礼盒会比普通家居小物更直接地改善使用感。',
    },
  },
  {
    id: 'mall-item-moon-theme',
    title: '月色桌面主题包',
    subtitle: '数字解锁 / 夜色配色',
    category: '数码',
    subCategory: '主题',
    price: 39,
    tags: ['主题', '数字商品', '夜色'],
    sceneTags: ['手机', '数字解锁', '自己买'],
    styleTags: ['安静', '夜色'],
    sensitivity: 'normal',
    destinationKinds: ['digital'],
    media: {
      fallbackEmoji: '🌙',
      fallbackIcon: 'package',
      templateKey: 'moon-theme',
      accentColor: '#6878b0',
      backgroundPreset: 'midnight-indigo',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '下单之后立刻到账的数字主题，更适合想马上看到变化的时候。',
      detailDescription: '这是一个偏夜色风格的数字主题包，强调冷静、安静和一点点朦胧的手机氛围。它没有物流，也不会进入普通物品，而是支付完成后直接解锁到你的数字物品里。适合想快速调整界面情绪的时候使用。',
      recommendationReason: '如果你现在更想马上获得可见变化，数字商品会比等待配送更直接。',
    },
  },
  {
    id: 'mall-item-bubble-pack',
    title: '柔雾聊天气泡包',
    subtitle: '数字解锁 / 轻玻璃感',
    category: '数码',
    subCategory: '聊天气泡',
    price: 29,
    tags: ['聊天', '主题', '数字商品'],
    sceneTags: ['手机', '数字解锁', '自己买'],
    styleTags: ['柔雾', '玻璃感'],
    sensitivity: 'normal',
    destinationKinds: ['digital'],
    media: {
      fallbackEmoji: '💬',
      fallbackIcon: 'package',
      templateKey: 'bubble-pack',
      accentColor: '#91a3c7',
      backgroundPreset: 'frost-blue',
      style: 'emoji',
    },
    copy: {
      cardBlurb: '适合想让聊天界面马上变得更柔和、更有层次的时候。',
      detailDescription: '这是一组偏轻玻璃感的聊天气泡样式，适合把界面整体调得更柔和一些。它属于数字解锁商品，购买后不会进入普通物品区，而是会直接进入数字物品。适合喜欢慢慢打磨设备感的人。',
      recommendationReason: '如果你已经在用 Bloom 很多聊天功能，这类小改动会比纯收藏更常被感受到。',
    },
  },
];

export function createDefaultMallData(): MallData {
  return {
    catalog: DEFAULT_CATALOG,
    cart: [],
    orders: [],
    ownedItems: [],
    deliveryFeed: [],
    wishlist: [],
    recentSearches: [],
    recentViewedItemIds: [],
    addresses: [],
    selectedAddressId: null,
    currentShoppingCompanionId: null,
  };
}

export { DEFAULT_CATALOG as DEFAULT_MALL_CATALOG };
