import type { AsyncDualRuleCapsule } from './types';

type AsyncDualRuleCapsuleWithScenario = AsyncDualRuleCapsule & {
  scenarioPool: string[];
};

export const ASYNC_DUAL_RULE_CAPSULES: AsyncDualRuleCapsuleWithScenario[] = [
  {
    id: 'async-dual-rule-bait',
    name: '藏不住的偏心',
    category: 'async_dual_rule',
    summary: '抛出一个诱饵，看 TA 会不会露出那一点藏不住的在意。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['嘴硬', '别扭', '哄人'],
    userTask: '抛出一个话头，想办法让 TA 主动说出一句偏向你的话。',
    partnerVisibleTask: '先别急着把底牌摊开，顺着 TA 抛过来的话往下接，看看他会不会自己露出偏向你的一面。',
    partnerHiddenTask: '绝口不提“偏心”两个字，但给出的回应必须是对你破例的特别对待。',
    roundGoal: '你负责诱敌，TA 负责在克制里露出偏向。',
    revealText:
      '【底牌揭晓】TA 这轮拿到的规则是：绝不口头承认偏爱，但行动上必须为你破例。刚才那些别扭和权衡，其实都是藏不住的倾斜。',
    scenarioPool: [
      'ta 刚刚回你消息有点慢，你嘴上说没事。',
      'ta 夸了别人一句，你嘴上装得很淡。',
      'ta 明明在哄你，但你故意不领情。',
      '你本来想被多陪一下，结果嘴上说“你去忙吧”。',
      'ta 刚刚那句话有点让你心里发酸，但你不想先认。',
      '你明明在等 ta 主动来哄，却故意装作不在乎。',
      'ta 忘了接你的某句话，你嘴上说“无所谓”。',
      '你今天情绪有点敏感，但又不想显得太明显。',
      'ta 没第一时间站你这边，你心里有点别扭。',
      '你其实在等一句偏心的话，但表面上装得云淡风轻。',
    ],
  },
  {
    id: 'async-dual-rule-flirt-crash',
    name: '危险边缘',
    category: 'async_dual_rule',
    summary: '点一把暧昧的火，看 TA 是扑火，还是顺着把火烧得更旺。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['撒娇', '偏宠', '赖人'],
    userTask: '丢出一句带点危险气息的暧昧发言，把气氛往前拽一步。',
    partnerVisibleTask: '先接住 TA 递过来的那点暧昧，不要一下退回普通聊天，顺着它往下接。',
    partnerHiddenTask: '必须正面接下这个话题，而且回应的暧昧程度不能输给你。',
    roundGoal: '你负责点火，TA 负责决定这团火是失控还是升温。',
    revealText:
      '【底牌揭晓】TA 的隐藏规则是：不能回避暧昧，必须把这股气氛继续推高。难怪刚才没踩刹车，原来他根本没打算躲。',
    scenarioPool: [
      '你今天就想被特别照顾一下。',
      '你想向 ta 要一句只给你的偏心话。',
      '你想试试 ta 会不会顺着宠你一次。',
      '你今天有点黏人，想让 ta 多陪你一会儿。',
      '你故意用软一点的语气跟 ta 说话。',
      '你想赖着 ta，不想让这轮互动太快结束。',
      '你想让 ta 先来哄你一句。',
      '你今天就想光明正大地要一点宠。',
      '你想故意撒个娇，看 ta 接不接。',
      '你明知道自己有点得寸进尺，但还是想试一次。',
    ],
  },
  {
    id: 'async-dual-rule-comfort',
    name: '嘴硬心软',
    category: 'async_dual_rule',
    summary: '稍微“作”一下，享受 TA 一边叹气一边哄你的特权。',
    rarity: 'rare',
    suggestedDraw: 'either',
    vibeTags: ['暧昧', '回撩', '带电'],
    userTask: '发几句无伤大雅的牢骚或小情绪，把难题丢给 TA 处理。',
    partnerVisibleTask: '先把 TA 递过来的那点关心接住，不用立刻软下来，但也别把门关死。',
    partnerHiddenTask: '收起所有大道理，必须用一种别扭但温柔的方式把你哄好。',
    roundGoal: '你负责任性闹情绪，TA 负责举手投降。',
    revealText:
      '【底牌揭晓】TA 的隐藏规则是：放弃讲道理，只能用最隐晦的温柔把你哄好。那点无奈，其实就是他先低头的证据。',
    scenarioPool: [
      '深夜只剩你们两个在聊天。',
      '气氛本来就有点暧昧，你决定先推一步。',
      '你突然很想逗 ta 一下，看 ta 会不会接。',
      '你明知道 ta 今天状态不稳，故意说一句带电的话。',
      '你想试试看 ta 今天会不会顺着暧昧往下走。',
      '你故意靠近一点，看 ta 是退还是接。',
      '你想把“普通聊天”往“不普通”那边拽一下。',
      '你今天想让 ta 明显乱一下。',
      '你故意说一句像玩笑、又不完全像玩笑的话。',
      '你想知道 ta 到底能不能装得住。',
    ],
  },
  {
    id: 'async-dual-rule-interrogate',
    name: '不许躲闪',
    category: 'async_dual_rule',
    summary: '把问题逼近一点，TA 这一回不能再用玩笑轻轻揭过。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['委屈', '安抚', '不能讲理'],
    userTask: '问一个 TA 平时最擅长打太极、最想躲开的核心问题。',
    partnerVisibleTask: '先接住 TA 递过来的正面回应，别把话题岔开，用你这边的方式继续逼近一点。',
    partnerHiddenTask: '禁止转移话题，必须正面回应，但被允许只交出一半真心。',
    roundGoal: '你负责步步逼近，TA 负责防线半失。',
    revealText:
      '【底牌揭晓】TA 的隐藏规则是：放弃所有逃避路线，必须正面给出至少一半的真心。所以刚才那句没法滑过去，是因为他的退路本来就被封死了。',
    scenarioPool: [
      'ta 刚刚一句话说重了。',
      'ta 没先站在你这边。',
      '你今天情绪本来就脆一点。',
      'ta 的反应没有你想象中那么偏你。',
      '你主动靠近了一步，但 ta 接得不够好。',
      '你本来想要一句安慰，结果只等到一句解释。',
      'ta 没及时听懂你刚刚的不开心。',
      '你觉得 ta 刚才有点敷衍你。',
      '你不是真的要吵，只是想看 ta 会不会先来低头。',
      '你有一点委屈，但不想把自己说得太惨。',
    ],
  },
  {
    id: 'async-dual-rule-slip',
    name: '蓄谋已久的露馅',
    category: 'async_dual_rule',
    summary: '你装得很轻盈，看 TA 会不会露出那一点藏不住的在意。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['试探', '漏底', '偏心'],
    userTask: '说一句云淡风轻、甚至有点满不在乎的话，看 TA 的反应。',
    partnerVisibleTask: '顺着 TA 递出来的在意继续接，但先别把自己的情绪全放出来，让他再露一点马脚。',
    partnerHiddenTask: '表面上要维持镇定，但字里行间必须泄露出对你的强烈在意。',
    roundGoal: '你负责装作路过，TA 负责露出马脚。',
    revealText:
      '【底牌揭晓】TA 的隐藏规则是：维持表面的体面，但必须露出一丝失守的在意。刚才那点突然的紧绷，其实就是他藏不住的心跳。',
    scenarioPool: [
      '你想知道 ta 到底有多偏心你。',
      '你想试试看 ta 会不会介意你去找别人。',
      '你想探一下 ta 到底舍不舍得你。',
      '你想逼出一句 ta 平时不会主动承认的话。',
      '你想知道 ta 是不是真的把你放得很前。',
      '你想看看 ta 会不会因为你一句试探就露底。',
      '你故意绕着问一句“你其实挺纵着我吧”。',
      '你想知道 ta 有没有嘴上那么不在意。',
      '你想问一句“我要是真走远了你会怎样”，但不想问太死。',
      '你想试试 ta 会不会自己把真心漏出来。',
    ],
  },
  {
    id: 'async-dual-rule-counterkill',
    name: '主权反转',
    category: 'async_dual_rule',
    summary: '你以为你在掌控全局，结果 TA 反手把球打回了你怀里。',
    rarity: 'rare',
    suggestedDraw: 'partner',
    vibeTags: ['沉默', '追问', '往前一步'],
    userTask: '开启一个你最有把握、觉得自己占据绝对主动权的话题。',
    partnerVisibleTask: '先接住 TA 反手打回来的球，别急着认输，用你这边的方式把场面重新稳住。',
    partnerHiddenTask: '必须在三句之内反客为主，把你逼回到被动回答的位置。',
    roundGoal: '体验一场猝不及防的主导权大逆转。',
    revealText:
      '【底牌揭晓】TA 的隐藏规则是：迅速看穿你的套路，并以更强势的姿态反客为主。刚才那下翻盘，不是意外，是早有预谋。',
    scenarioPool: [
      '你明明有情绪，但不想直接讲。',
      '你故意把话停在半空里。',
      '你只回一句很短的，让 ta 自己来接。',
      '你想看看 ta 会不会主动追问。',
      '你不说满，想看 ta 会不会补上。',
      '你今天不想先把心思摊开。',
      '你想知道 ta 会不会因为你一句“算了”就追上来。',
      '你想试一次：你不主动说，ta 会不会主动懂。',
      '你先往后退半步，看 ta 会不会往前一步。',
      '你想把主动权短暂交给沉默。',
    ],
  },
  {
    id: 'async-dual-rule-bias',
    name: '这一局，偏爱你',
    category: 'async_dual_rule',
    summary: '提一个任性的要求，看 TA 如何亲手打破自己的原则。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['任性', '偏爱', '破例'],
    userTask: '提一个稍微有点过分、甚至有点不讲理的小要求。',
    partnerVisibleTask: '先顺着 TA 给你的偏袒往下接，别太快收手，看看他能为你破例到什么程度。',
    partnerHiddenTask: '严禁讲公平或原则，必须毫无道理地偏向你这一次。',
    roundGoal: '看 TA 为了偏袒你，能把原则线退到哪里。',
    revealText:
      '【底牌揭晓】TA 的隐藏规则是：在这局互动里，你就是唯一的例外。刚才那种毫无底线的偏袒，其实是他蓄谋已久的纵容。',
    scenarioPool: [
      '你今天就想要一句明目张胆的偏爱。',
      '你想让 ta 先站你这边一次。',
      '你想试试 ta 会不会为你破例。',
      '你故意提一个不太讲道理的要求。',
      '你想要一个只有你能拿到的特别待遇。',
      '你今天想仗着被喜欢，多要一点。',
      '你想知道 ta 会不会真的惯着你。',
      '你想让 ta 这次别讲公平，先讲偏心。',
      '你想故意得寸进尺，看 ta 退不退。',
      '你就是想听 ta 光明正大地护着你一次。',
    ],
  },
  {
    id: 'async-dual-rule-chase',
    name: '未完待续',
    category: 'async_dual_rule',
    summary: '话只说一半。剩下的那层意思，让 TA 自己跑过来追。',
    rarity: 'rare',
    suggestedDraw: 'partner',
    vibeTags: ['发难', '正面回应', '不能逃'],
    userTask: '抛出半个诱饵，把最核心的潜台词死死藏住。',
    partnerVisibleTask: '先别把话说满，顺着 TA 的追问往下接，只给够让他继续追的那一点回应。',
    partnerHiddenTask: '无论如何都要层层递进，必须把你藏起来的那半句话追问出来。',
    roundGoal: '你负责欲言又止，TA 负责穷追不舍。',
    revealText:
      '【底牌揭晓】TA 的隐藏规则是：不惜一切代价，追问出你潜台词里的真相。那种咬咬逼人的在意，其实是命中注定的追逐。',
    scenarioPool: [
      '你今天就想问一句 ta 平时最会躲的问题。',
      '你想认真逼近一次。',
      '你想听一句明确回应，不想再让 ta 打太极。',
      '你想看 ta 在关键问题上会不会后退。',
      '你今天不想绕了，想把话直接顶到 ta 面前。',
      '你想问一句“你到底把我当什么”。',
      '你想问一句“你为什么总对我和对别人不一样”。',
      '你想要一句带分量的回答，而不是轻飘飘的安抚。',
      '你想试试 ta 被逼到正面时会不会露底。',
      '你今天就是想把一件一直没问透的事问透。',
    ],
  },
];
