import type { TruthVariantCapsule } from './types';

export const TRUTH_VARIANT_CAPSULES: TruthVariantCapsule[] = [
  {
    id: 'truth-variant-no-direct-answer',
    name: '锁定谎的答案',
    category: 'truth_variant',
    summary: '触发【闪避】状态：禁用肯定或否定词，用绕回答代替直白。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['禁止直球', '语言闪避', '漏风'],
    answerRule: '这一次，把“是”和“不是”藏起来。',
    feeling: '语言被加了枷锁，心意却总会透过缝隙漏出来。绕着走，反而更撩拨。',
    questionPool: [
      '你最想我在什么时候，一言不发地抱紧你？',
      '如果我偏要对你撒娇，你能撑住几秒不理我？',
      '其实……你一直都很享受我黏着你，对吧？',
      '我要是今晚赖着不走，你会舍不得赶我出门吗？',
    ],
  },
  {
    id: 'truth-variant-half-admit',
    name: '半透明心事',
    category: 'truth_variant',
    summary: '触发【限流】状态：真心话加载进度仅限 50%。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['进度条50%', '若隐若现', '拉扯'],
    answerRule: '只准交出一半的底牌，剩下的要捂严实。',
    feeling: '像隔着一层磨砂玻璃，让TA只能看清一半的你。说太满，游戏就提前结束了。',
    questionPool: [
      '在我面前，你最不想硬撑的瞬间是什么时候？',
      '老实交代，有没有偷偷反复看过我们的聊天记录？',
      '你最不想让我看穿，却又最容易暴露的在意是什么？',
      '如果今天只能承认一半，你会承认你对我哪一点最偏心？',
    ],
  },
  {
    id: 'truth-variant-tsundere-truth',
    name: '防御性伪装',
    category: 'truth_variant',
    summary: '装备【护甲】：必须输出真实意图，但强制附加“傲娇”Debuff。',
    rarity: 'common',
    suggestedDraw: 'partner',
    vibeTags: ['战术嘴硬', '别扭惹人爱', '真心底色'],
    answerRule: '真心可以给，但态度绝不能太乖。',
    feeling: '越是柔软的心，越要用最硬的壳包起来。让TA自己去猜面具底下的温度。',
    questionPool: [
      '要是我真生气不理你了，你打算怎么收场？',
      '我平时那些无理取闹的小脾气，你是忍着，还是偷偷乐着？',
      '你是不是嘴上嫌我烦，其实视线根本没离开过我？',
      '你最想凶我，却在看到我眼睛那一刻就泄气的时候，在想什么？',
    ],
  },
  {
    id: 'truth-variant-incomplete',
    name: '未完待续',
    category: 'truth_variant',
    summary: '触发【截断】效果：话音落在一半，将想象空间交还给对方。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['极致留白', '话音悬空', '遐想'],
    answerRule: '接住这个问题，但记得在最关键的地方停住。',
    feeling: '点到为止就够了。剩下的剧情，让TA自己用脑补来填满。',
    questionPool: [
      '在你眼里，我最让你心软的瞬间是哪一刻？',
      '给未来的我们留一句线索吧。（要足够特别的那种）',
      '你最想告诉我、却总是咽下半句的那段话，是什么？',
      '你对我妥协的时候，最怕我听懂的是哪一点？',
    ],
  },
  {
    id: 'truth-variant-detour-then-admit',
    name: '回旋落点',
    category: 'truth_variant',
    summary: '路径规划限制：允许偏航，但最终判定点必须命中真心。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['战术后仰', '最终破防', '宿命感'],
    answerRule: '可以先带着他绕个圈子，别一上来就缴械。',
    feeling: '所有的挣扎和嘴硬都只是前戏，最终，表达你的心意。',
    questionPool: [
      '如果有一天冷战了，你觉得谁会先熬不住低头？',
      '遇到分歧的时候，你是想和我据理力争，还是其实只想被我哄？',
      '你是不是偶尔也会害怕，万一我真的不惯着你了怎么办？',
      '你最想嘴硬撑到底，最后却总会对我举手投降的是什么事？',
    ],
  },
  {
    id: 'truth-variant-one-line',
    name: '一击必杀',
    category: 'truth_variant',
    summary: '字符输入限制：单回合定胜负，禁用长篇大论，不可撤回。',
    rarity: 'rare',
    suggestedDraw: 'either',
    vibeTags: ['极简绝杀', '寸止', '余音绕梁'],
    answerRule: '这一次，只能用一句话定胜负。',
    feeling: '一句话就够了。不能太长，但要让人记住。',
    questionPool: [
      '今晚闭上眼睛前，你最想听到我跟你说哪三个字？',
      '如果能预支未来，最想和我马上兑现的一件小事是？',
      '用一句话告诉我，我在你这儿，到底算多特殊的例外。',
      '只准说一句：你最舍不得我从你生命里拿走什么？',
    ],
  },
  {
    id: 'truth-variant-no-reasoning',
    name: '感性过载',
    category: 'truth_variant',
    summary: '禁用【逻辑】模块：禁止分析与说理，仅允许【情绪】直出。',
    rarity: 'common',
    suggestedDraw: 'partner',
    vibeTags: ['逻辑断网', '直觉本能', '情绪失守'],
    answerRule: '讲道理的频道已关闭，现在只需要你的态度。',
    feeling: '在偏爱面前，理智一文不值。别找借口，直接把情绪砸过来。',
    questionPool: [
      '吵得最凶的时候，你心里其实是想我讲道理，还是想我直接抱紧你？',
      '如果以后我们闹别扭，你希望我下意识的第一反应是什么？',
      '如果我现在毫无逻辑地跟你闹，你接还是不接？',
      '要是我现在不讲理地说一句“快哄我”，你是认命，还是继续扛着？',
    ],
  },
  {
    id: 'truth-variant-cannot-ignore',
    name: '强制对视',
    category: 'truth_variant',
    summary: '释放【锁定】技：目标无法进行【闪避】或【滑过】判定。',
    rarity: 'common',
    suggestedDraw: 'either',
    vibeTags: ['不可闪避', '直球对决', '眼神锁定'],
    answerRule: '这道题带了追踪锁定，装作没听见是不可能的。',
    feeling: '不用立刻交代全部，但这一次，你必须直视我的眼睛给出反应。逃不掉的。',
    questionPool: [
      '说实话，你心里是更希望我为你吃醋，还是希望我懂事大方？',
      '世界末日逃生只能带一样，带我，还是带你的全部身家？',
      '我认认真真问你一次：你对我双标得这么明显，你自己知道吗？',
      '看着我的眼睛回答：你到底，舍不舍得看我受半点委屈？',
    ],
  },
  {
    id: 'truth-variant-vague-confession',
    name: '心跳摩斯码',
    category: 'truth_variant',
    summary: '触发【加密】传递：屏蔽直接的爱意表达词，用细节代替直白。',
    rarity: 'rare',
    suggestedDraw: 'partner',
    vibeTags: ['朦胧滤镜', '隐喻告白', '高级暧昧'],
    answerRule: '喜欢不能明说，得揉碎了藏在话里递过去。',
    feeling: '不许说那几个字，但TA听完之后到底会怎么想呢？',
    questionPool: [
      '如果不允许说话，你会选哪个动作来证明你现在很想我？（牵手 / 拥抱 / 咬一口）',
      '在什么样光线和氛围下，你会产生想偷偷亲我的冲动？',
      '换个高级点的方式告诉我，为什么你总是舍不得推开我？',
      '把喜欢藏起来，然后告诉我，你最想在这段关系里占据什么位置？',
    ],
  },
  {
    id: 'truth-variant-privileged-question',
    name: '禁区通行证',
    category: 'truth_variant',
    summary: '获得【一次性豁免权】：无视安全距离限制，强制进行一次深度试探。',
    rarity: 'special',
    suggestedDraw: 'self',
    vibeTags: ['越权访问', '危险试探', '逼近底线'],
    answerRule: '仗着此时的特权，把平时不敢问的，大胆往前递一步。',
    feeling: '借着游戏的名义，堂而皇之地越界。这一回，TA可别想躲开。',
    questionPool: [
      '如果我约会迟到，还理直气壮，你会真的生我的气吗？',
      '在你潜意识里，我是更像需要顺毛摸的猫，还是需要牵牢的狗？',
      '老实说，你最看不得我对谁展露和你一样的笑容？',
      '如果我今天主动得稍微有点“过火”，你会惊吓多一点，还是暗爽多一点？',
    ],
  },
];
