export const GROUP_OFFLINE_HIGHLIGHT_COLOR_OPTIONS = [
  '#92EBF2',
  '#FFE27A',
  '#FBB6CE',
  '#C4B5FD',
  '#9AE6B4',
  '#FDBA74',
];

export const GROUP_OFFLINE_BODY_TEXT_COLOR_OPTIONS = [
  '#FFFFFF',
  '#F8FBFF',
  '#F6F7FB',
  '#FFF7ED',
  '#F3FAFF',
  '#F6FFF8',
];

export const DEFAULT_GROUP_OFFLINE_HIGHLIGHT_COLOR = GROUP_OFFLINE_HIGHLIGHT_COLOR_OPTIONS[0];
export const DEFAULT_GROUP_OFFLINE_BODY_TEXT_COLOR = GROUP_OFFLINE_BODY_TEXT_COLOR_OPTIONS[0];
