export type BasicChatExpression = {
  value: string;
  kind: 'emoji' | 'kaomoji';
};

export const BASIC_CHAT_EXPRESSIONS: BasicChatExpression[] = [
  { value: '😀', kind: 'emoji' },
  { value: '🙂', kind: 'emoji' },
  { value: '😺', kind: 'emoji' },
  { value: '😚', kind: 'emoji' },
  { value: '😳', kind: 'emoji' },
  { value: '🥺', kind: 'emoji' },
  { value: '😑', kind: 'emoji' },
  { value: '😎', kind: 'emoji' },
  { value: '😹', kind: 'emoji' },
  { value: '😭', kind: 'emoji' },
  { value: '😤', kind: 'emoji' },
  { value: '😶', kind: 'emoji' },
  { value: '❤️', kind: 'emoji' },
  { value: '💗', kind: 'emoji' },
  { value: '💕', kind: 'emoji' },
  { value: '🙄', kind: 'emoji' },
  { value: '🙏', kind: 'emoji' },
  { value: '🎀', kind: 'emoji' },
  { value: '🎉', kind: 'emoji' },
  { value: '🌙', kind: 'emoji' },
  { value: '✨', kind: 'emoji' },
  { value: '(づ ᴗ _ᴗ)づ', kind: 'kaomoji' },
  { value: '૮₍ ˶ᵔ ᵕ ᵔ˶ ₎ა', kind: 'kaomoji' },
  { value: '(｡>﹏<｡)', kind: 'kaomoji' },
  { value: '(¬_¬ )', kind: 'kaomoji' },
  { value: '( ᵕᴗᵕ )', kind: 'kaomoji' },
  { value: '(*˘︶˘*).｡.:*', kind: 'kaomoji' },
  { value: '(っ˘ڡ˘ς)', kind: 'kaomoji' },
  { value: '(｡･ω･｡)', kind: 'kaomoji' },
  { value: '( •̀ ω •́ )✧', kind: 'kaomoji' },
  { value: '(ノ_<。)', kind: 'kaomoji' },
  { value: '( ˘ ³˘)♥', kind: 'kaomoji' },
  { value: '(╥﹏╥)', kind: 'kaomoji' },
  { value: '(つω`｡)', kind: 'kaomoji' },
  { value: 'o(≧▽≦)o', kind: 'kaomoji' },
  { value: '(￣▽￣)~*', kind: 'kaomoji' },
  { value: '(ง •_•)ง', kind: 'kaomoji' },
  { value: '(｡•̀ᴗ-)✧', kind: 'kaomoji' },
  { value: '(๑´ㅂ`๑)', kind: 'kaomoji' },
  { value: '(っ´▽`)っ', kind: 'kaomoji' },
  { value: '(っ´ω`)ﾉ(╥ω╥)', kind: 'kaomoji' },
  { value: '(๑•̀ㅂ•́)و✧', kind: 'kaomoji' },
  { value: '( ˶ˆᗜˆ˵ )', kind: 'kaomoji' },
  { value: '(｡•́︿•̀｡)', kind: 'kaomoji' },
  { value: '(っ ̯ -｡)', kind: 'kaomoji' },
  { value: '(ฅ' + "'" + 'ω' + "'" + 'ฅ)', kind: 'kaomoji' },
  { value: '(。•ω•。)ノ♡', kind: 'kaomoji' },
];
