name = "bloom-wechat-bridge-do"
main = "src/index.js"
compatibility_date = "2026-04-26"

[[durable_objects.bindings]]
name = "WECHAT_BRIDGE_DO"
class_name = "WechatBridgeDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WechatBridgeDurableObject"]
